---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  nodeMeshMaxRestartTime: 120s
  asNumber: 64500
  serviceClusterIPs:
    - cidr: 10.96.0.0/12
  serviceLoadBalancerIPs:
    - cidr: 10.1.15.0/24
  listenPort: 179
  bindMode: NodeIP
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: my-bgp-peer
spec:
  peerIP: 10.1.0.1
  asNumber: 64501
