---
define: &containerPort 80

common:
  app:
    servicePort: 80
    containerPort: *containerPort

  # deployment
  deployment:
    memoryRequest: 512M
    cpuRequest: 100m
    memoryLimit: 1024M
    cpuLimit: 250m
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%

  # container
  image:
    repositorySettings:
      isPrivate: false
      secretName: null
    repository: gotify/server
    tag: 2.4.0
    pullPolicy: Always

  # ingress
  ingress:
    enabled: true
    hostName: gotify.k8s.$MYTLD
    tls:
      enabled: true
      secretName: ""
    # For Ingress CRD
    ingressClassName: nginx
    # For IngressRoute CRD
    isIngressRoute: true
    entrypoint: websecure
    certResolver: letsencrypt-prod  # leave empty if you don't use, tls.enabled must be true and secretName must me empty

  # env variables
  variables:
    secret:
      GOTIFY_DEFAULTUSER_NAME: admin
      GOTIFY_DEFAULTUSER_PASS: admin
    nonSecret:
      GOTIFY_DATABASE_DIALECT: sqlite3  # do not use if you go HA.
      GOTIFY_DATABASE_CONNECTION: data/gotify.db
      GOTIFY_PASSSTRENGTH: 10
      GOTIFY_UPLOADEDIMAGESDIR: data/images
      GOTIFY_PLUGINSDIR: data/plugins
      TZ: UTC

  # horizontal autoscaler
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    avgCpuUtilization: 50

  # startupProbe
  startupProbeEnabled: true
  startupProbe:
    httpGet:
      path: "/"
      port: *containerPort
    periodSeconds: 10
    failureThreshold: 20
    timeoutSeconds: 1

  # readinessProbe
  readinessProbeEnabled: true
  readinessProbe:
    httpGet:
      path: "/"
      port: *containerPort
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 2
    timeoutSeconds: 3

  # livenessProbe
  livenessProbeEnabled: true
  livenessProbe:
    httpGet:
      path: "/"
      port: *containerPort
    initialDelaySeconds: 30
    periodSeconds: 60
    failureThreshold: 1
    timeoutSeconds: 3

  persistence:
    enabled: true
    volumes:
      - name: "data"
        storageClassName: ""  # leave empty if you want to use default
        size: "10Gi"
        pvcClaim: ""  # Fill only if you want to use existing pvc
        containerMount: "/app/data/"

  tests:
    classicHttp:  # default helm test method
      enabled: true
    curlHostHeader:  # curl using ingress.hostName as Host in header
      enabled: true
      path: "/"
