apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: $YOU@$YOUREMAILSERVICE
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
